name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com/' # Quan trọng: Chỉ định registry

      - name: Configure Yarn for GitHub Packages
        run: |
          yarn config set npmAuthToken "${{ secrets.SSH_PRIVATE_KEY }}" # Thiết lập token
          yarn config set npmRegistryServer "https://npm.pkg.github.com/" # Thiết lập registry

      - run: yarn install --frozen-lockfile
      - run: yarn build --if-present
      - run: yarn test
