name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn' # Thay đổi từ 'npm' sang 'yarn'
    - run: yarn install # Thay đổi từ 'npm ci' sang 'yarn install'
    - run: yarn build --if-present # Thay đổi từ 'npm run build' sang 'yarn build'
    - run: yarn test # Thay đổi từ 'npm test' sang 'yarn test'
